# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -o deploy

    - name: Empacotar conteúdo da pasta
      run: cd deploy && zip -r ../deploy.zip ./*

    - name:  Deploy to EB
      uses:  einaregilsson/beanstalk-deploy@v22
      
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        aws_access_key:  ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key:  ${{ env.AWS_SECRET_ACCESS_KEY }}
        application_name:  .Net Core Devops
        environment_name:  NetCoreDevops-env
        version_label:  ${{ github.workflow }}-${{ github.run_id }}
        region:  us-east-2
        deployment_package:  deploy.zip

